name: cicd pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: validate with maven
        run: mvn validate
      - name: compile with maven
        run: mvn compile
      - name: test with maven
        run: mvn test
      - name: pacakage with maven
        run: mvn package

      - uses: actions/upload-artifact@v4
        with:
          name: war
          path: target/*.war

  deploy-ec2:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v4 
          with:
            name: war
        
        - name: copy war to ec2
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: '*.war'
            target: '/home/ubuntu/'

        - name: copy war to tomcat
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              sudo cp /home/ubuntu/target/*.war /opt/tomcat/webapps/

  deploy-env:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v4 
          with:
            name: war
        
        - name: copy war to ec2
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.ENV_HOST }}
            username: ${{ secrets.ENV_USERNAME }}
            key: ${{ secrets.ENV_SSH_KEY }}
            source: '*.war'
            target: '/home/ubuntu/'

        - name: copy war to tomcat
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.ENV_HOST }}
            username: ${{ secrets.ENV_USERNAME }}
            key: ${{ secrets.ENV_SSH_KEY }}
            script: |
              sudo cp /home/ubuntu/target/*.war /opt/tomcat/webapps/
          
